# Etapa 1: instalar dependencias
FROM python:3.12 AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt


# Etapa 2: imagen de ejecución
FROM python:3.12-slim

WORKDIR /app

RUN useradd --create-home --shell /bin/bash appuser

COPY --from=builder --chown=appuser:appuser \
    /root/.local /home/appuser/.local

ENV PATH="/home/appuser/.local/bin:${PATH}"
ENV PYTHONUNBUFFERED=1

COPY --chown=appuser:appuser . .

ARG APP_VERSION=v1
ENV APP_VERSION=${APP_VERSION}

USER appuser

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]